namespace NServiceBus.AzureFunctions.Tests;

using Azure.Messaging.ServiceBus;
using AzureServiceBus;
using BitFaster.Caching;
using BitFaster.Caching.Lru;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Logging.Testing;
using NUnit.Framework;
using Transport;
using NServiceBus;

[TestFixture]
public class MessageProcessorTests
{
    [Test]
    public async Task Should_expose_native_message_id_headers_and_body_on_message_context()
    {
        var expectedMessageId = "test-message-id-123";
        var expectedBody = new byte[] { 1, 2, 3, 4 };
        var expectedHeaderKey = "custom-header";
        var expectedHeaderValue = "header-value";
        var expectedReplyTo = "reply-queue";
        var expectedCorrelationId = "correlation-abc";
        var expectedContentType = "some/content-type";

        var message = ServiceBusModelFactory.ServiceBusReceivedMessage(
            messageId: expectedMessageId,
            properties: new Dictionary<string, object> { { expectedHeaderKey, expectedHeaderValue } },
            body: new BinaryData(expectedBody),
            replyTo: expectedReplyTo,
            correlationId: expectedCorrelationId,
            contentType: expectedContentType
        );

        var result = await ProcessMessage(
            message: message
        );

        var messageContext = result.MessageContext;

        using (Assert.EnterMultipleScope())
        {
            Assert.That(messageContext, Is.Not.Null, "MessageContext should not be null");
            Assert.That(messageContext!.NativeMessageId, Is.EqualTo(expectedMessageId), "MessageContext should expose the native message id");
            Assert.That(messageContext.Headers.ContainsKey(expectedHeaderKey), Is.True, "MessageContext should expose the custom header");
            Assert.That(messageContext.Headers[expectedHeaderKey], Is.EqualTo(expectedHeaderValue), "MessageContext should expose the correct header value");
            Assert.That(messageContext.Body.ToArray(), Is.EqualTo(expectedBody).AsCollection, "MessageContext should expose the correct message body");
            Assert.That(messageContext.Headers.ContainsKey(Headers.CorrelationId), Is.True, "Native CorrelationId should be upconverted to the CorrelationId header");
            Assert.That(messageContext.Headers[Headers.CorrelationId], Is.EqualTo(expectedCorrelationId), "Headers should expose the correct CorrelationId value");
            Assert.That(messageContext.Headers.ContainsKey(Headers.ReplyToAddress), Is.True, "Native ReplyTo should be upconverted to the ReplyToAddress header");
            Assert.That(messageContext.Headers[Headers.ReplyToAddress], Is.EqualTo(expectedReplyTo), "Headers should expose the correct ReplyTo header value");
            Assert.That(messageContext.Headers.ContainsKey(Headers.ContentType), Is.True, "Native ContentType should be upconverted to the ContentType header");
            Assert.That(messageContext.Headers[Headers.ContentType], Is.EqualTo(expectedContentType), "Headers should expose the correct ContentType header value");
        }
    }

    [Test]
    public async Task Should_derive_message_id_from_enqueued_time_and_sequence_number_if_no_native_id_is_present()
    {
        var sequenceNumber = 42L;
        var enqueuedTime = DateTimeOffset.UtcNow;
        var expectedMessageId = GuidHelper.CreateVersion8(enqueuedTime, sequenceNumber).ToString();

        string? firstMessageId = null;
        string? secondMessageId = null;
        var message = ServiceBusModelFactory.ServiceBusReceivedMessage(sequenceNumber: sequenceNumber, enqueuedTime: enqueuedTime);

        await ProcessMessage(message: message, onMessage: (context, _) => { firstMessageId = context.NativeMessageId; return Task.CompletedTask; });
        await ProcessMessage(message: message, onMessage: (context, _) => { secondMessageId = context.NativeMessageId; return Task.CompletedTask; });

        using (Assert.EnterMultipleScope())
        {
            Assert.That(firstMessageId, Is.EqualTo(expectedMessageId), "MessageId should be derived from enqueued time and sequence number");
            Assert.That(secondMessageId, Is.EqualTo(firstMessageId), "MessageId should be stable across processing attempts");
        }
    }

    [Test]
    public async Task Should_use_auto_generated_message_id_if_present()
    {
        string? messageId = null;
        var autoGeneratedMessageId = Guid.NewGuid().ToString();
        var message = ServiceBusModelFactory.ServiceBusReceivedMessage(properties: new Dictionary<string, object> { { Headers.MessageId, autoGeneratedMessageId } });
        var result = await ProcessMessage(
            message: message,
            onMessage: (context, _) =>
            {
                messageId = context.NativeMessageId;
                return Task.CompletedTask;
            });
        using (Assert.EnterMultipleScope())
        {
            Assert.That(result.MessageActions.WasCompleted, Is.True, "Message should be completed");
            Assert.That(messageId, Is.EqualTo(autoGeneratedMessageId), "Auto generated message id should used as message id");
        }
    }

    [Test]
    public async Task Should_complete_messages_with_sequence_number_derived_id_immediately_if_previous_processing_attempt_was_successful()
    {
        var completedMessagesCache = new FastConcurrentLru<string, bool>(1_000);
        var message = ServiceBusModelFactory.ServiceBusReceivedMessage(sequenceNumber: 99L);

        var firstProcessingResult = await ProcessMessage(
            message: message,
            completedMessagesCache: completedMessagesCache,
            messageActions: new TestableMessageActions { CompleteMessage = (_, _) => throw new Exception("simulated complete exception") });

        using (Assert.EnterMultipleScope())
        {
            Assert.That(firstProcessingResult.OnMessageWasCalled, Is.True, "OnMessage should be called");
            Assert.That(firstProcessingResult.MessageActions.WasCompleted, Is.True, "Message should be completed");
        }

        var secondProcessingResult = await ProcessMessage(
            message: message,
            completedMessagesCache: completedMessagesCache);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(secondProcessingResult.OnMessageWasCalled, Is.False, "OnMessage should not be called on second delivery");
            Assert.That(secondProcessingResult.MessageActions.WasCompleted, Is.True, "Message should be completed on second delivery");
        }
    }

    [Test]
    public async Task Should_complete_messages_immediately_if_previous_processing_attempt_was_successful()
    {
        var completedMessagesCache = new FastConcurrentLru<string, bool>(1_000);
        var message = ServiceBusModelFactory.ServiceBusReceivedMessage(messageId: Guid.NewGuid().ToString());

        var firstProcessingResult = await ProcessMessage(
            message: message,
            completedMessagesCache: completedMessagesCache,
            messageActions: new TestableMessageActions { CompleteMessage = (_, _) => throw new Exception("simulated complete exception") });

        using (Assert.EnterMultipleScope())
        {
            Assert.That(firstProcessingResult.OnMessageWasCalled, Is.True, "OnMessage should be called");
            Assert.That(firstProcessingResult.MessageActions.WasCompleted, Is.True, "Message should be completed");
        }

        var secondProcessingResult = await ProcessMessage(
            message: message,
            completedMessagesCache: completedMessagesCache);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(secondProcessingResult.OnMessageWasCalled, Is.False, "OnMessage should not be called");
            Assert.That(secondProcessingResult.MessageActions.WasCompleted, Is.True, "Message should be completed");
        }
    }

    [Test]
    public async Task Should_complete_when_on_message_succeeds()
    {
        var result = await ProcessMessage(
            onMessage: (_, _) => Task.CompletedTask);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(result.OnMessageWasCalled, Is.True, "OnMessage should be called");
            Assert.That(result.OnErrorWasCalled, Is.False, "OnError should not be called");
            Assert.That(result.MessageActions.WasCompleted, Is.True, "Message should be completed");
            Assert.That(result.MessageActions.WasAbandoned, Is.False, "Message should not be abandoned");
        }
    }

    [Test]
    public async Task Should_abandon_when_on_message_fails_and_retry_is_requested()
    {
        var result = await ProcessMessage(
            onMessage: (_, _) => throw new Exception("simulated exception"),
            onError: (_, _) => Task.FromResult(ErrorHandleResult.RetryRequired));

        using (Assert.EnterMultipleScope())
        {
            Assert.That(result.OnMessageWasCalled, Is.True, "OnMessage should be called");
            Assert.That(result.OnErrorWasCalled, Is.True, "OnError should be called");
            Assert.That(result.MessageActions.WasCompleted, Is.False, "Message should not be completed");
            Assert.That(result.MessageActions.WasAbandoned, Is.True, "Message should be abandoned");
        }
    }

    [Test]
    public async Task Should_complete_when_on_message_fails_and_failure_is_marked_as_handled()
    {
        var result = await ProcessMessage(
            onMessage: (_, _) => throw new Exception("simulated exception"),
            onError: (_, _) => Task.FromResult(ErrorHandleResult.Handled));

        using (Assert.EnterMultipleScope())
        {
            Assert.That(result.OnMessageWasCalled, Is.True, "OnMessage should be called");
            Assert.That(result.OnErrorWasCalled, Is.True, "OnError should be called");
            Assert.That(result.MessageActions.WasCompleted, Is.True, "Message should be completed");
            Assert.That(result.MessageActions.WasAbandoned, Is.False, "Message should not be abandoned");
        }
    }

    [Test]
    public async Task Should_abandon_when_on_error_throws_transient_service_bus_exception()
    {
        var result = await ProcessMessage(
            onMessage: (_, _) => throw new Exception("simulated exception"),
            onError: (_, _) => throw new ServiceBusException("simulated transient exception", ServiceBusFailureReason.ServiceBusy)); //ServiceBusy is transient

        using (Assert.EnterMultipleScope())
        {
            Assert.That(result.MessageActions.WasCompleted, Is.False, "Message should not be completed");
            Assert.That(result.MessageActions.WasAbandoned, Is.True, "Message should be abandoned if onError throws");
            Assert.That(result.MessageActions.WasDeadLettered, Is.False, "Message should not be dead lettered");
        }
    }

    [Test]
    public async Task Should_abandon_when_on_error_throws_lock_lost_service_bus_exception()
    {
        var result = await ProcessMessage(
            onMessage: (_, _) => throw new Exception("simulated exception"),
            onError: (_, _) => throw new ServiceBusException("simulated lock lost exception", ServiceBusFailureReason.MessageLockLost));

        using (Assert.EnterMultipleScope())
        {
            Assert.That(result.MessageActions.WasCompleted, Is.False, "Message should not be completed");
            Assert.That(result.MessageActions.WasAbandoned, Is.True, "Message should be abandoned if onError throws");
            Assert.That(result.MessageActions.WasDeadLettered, Is.False, "Message should not be dead lettered");
        }
    }

    [Test]
    public async Task Should_dlq_when_on_error_throws_non_transient_exception()
    {
        var exception = new Exception("simulated exception in on error");
        var result = await ProcessMessage(
            onMessage: (_, _) => throw new Exception("simulated exception"),
            onError: (_, _) => throw exception);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(result.MessageActions.WasCompleted, Is.False, "Message should not be completed");
            Assert.That(result.MessageActions.WasAbandoned, Is.False, "Message should not be abandoned if onError throws");
            Assert.That(result.MessageActions.WasDeadLettered, Is.True, "Message should be dead lettered");
        }
    }

    [Test]
    public async Task Should_dlq_message_if_requested()
    {
        var expectedDlqReason = "some reason";
        var expectedDlqDescription = "some description";

        var result = await ProcessMessage(
            onMessage: (_, _) => throw new Exception("simulated exception"),
            onError: (errorContext, _) =>
            {
                errorContext.TransportTransaction.Set(new DeadLetterRequest(expectedDlqReason, expectedDlqDescription, new Dictionary<string, object> { { "MyProperty", "MyValue" } }));
                return Task.FromResult(ErrorHandleResult.Handled);
            });

        using (Assert.EnterMultipleScope())
        {
            Assert.That(result.MessageActions.WasCompleted, Is.False, "Message should not be completed");
            Assert.That(result.MessageActions.WasAbandoned, Is.False, "Message should not be abandoned");
            Assert.That(result.MessageActions.WasDeadLettered, Is.True, "Message should be dead lettered");
            Assert.That(result.LogCollector.LatestRecord.Level, Is.EqualTo(Microsoft.Extensions.Logging.LogLevel.Error), "DLQ requests should be logged as error");
            Assert.That(result.LogCollector.LatestRecord.Message, Does.Contain(expectedDlqReason), "Should log DLQ reason");
            Assert.That(result.LogCollector.LatestRecord.Message, Does.Contain(expectedDlqDescription), "Should log DLQ description");
        }
    }

    [Test]
    public async Task Should_expose_the_service_bus_message_on_both_message_and_error_context()
    {
        var message = ServiceBusModelFactory.ServiceBusReceivedMessage(messageId: Guid.NewGuid().ToString());

        var result = await ProcessMessage(
            message: message,
            onMessage: (_, _) => throw new Exception("simulated exception"));

        using (Assert.EnterMultipleScope())
        {
            Assert.That(result.MessageContext?.Extensions.Get<ServiceBusReceivedMessage>(), Is.SameAs(message), "MessageContext should contain the ServiceBusReceivedMessage");
            Assert.That(result.ErrorContext?.Extensions.Get<ServiceBusReceivedMessage>(), Is.SameAs(message), "ErrorContext should contain the ServiceBusReceivedMessage");
        }
    }

    [Test]
    public async Task Should_abandon_when_token_is_cancelled_and_not_invoke_onerror()
    {
        var result = await ProcessMessage(
            onMessage: (_, ct) =>
            {
                ct.ThrowIfCancellationRequested();
                return Task.CompletedTask;
            },
            cancellationToken: new CancellationToken(true)
        );

        using (Assert.EnterMultipleScope())
        {
            Assert.That(result.OnErrorWasCalled, Is.False, "OnError should not be called");
            Assert.That(result.MessageActions.WasCompleted, Is.False, "Message should not be completed");
            Assert.That(result.MessageActions.WasAbandoned, Is.True, "Message should be abandoned");
            Assert.That(result.LogCollector.LatestRecord.Level, Is.EqualTo(Microsoft.Extensions.Logging.LogLevel.Debug), "Cancellation should be logged as debug");
            Assert.That(result.LogCollector.LatestRecord.Message, Does.Contain("Message processing canceled"), "Should log debug when processing canceled");
            Assert.That(result.LogCollector.LatestRecord.Exception, Is.InstanceOf<OperationCanceledException>());
        }
    }

    [Test]
    public async Task Should_abandon_on_error_when_token_is_cancelled()
    {
        var result = await ProcessMessage(
            onMessage: (_, _) => throw new Exception("simulated exception"),
            onError: (_, ct) =>
            {
                ct.ThrowIfCancellationRequested();
                return Task.FromResult(ErrorHandleResult.Handled);
            },
            cancellationToken: new CancellationToken(true)
        );

        using (Assert.EnterMultipleScope())
        {
            Assert.That(result.MessageActions.WasCompleted, Is.False, "Message should not be completed");
            Assert.That(result.MessageActions.WasAbandoned, Is.True, "Message should be abandoned");
            Assert.That(result.LogCollector.LatestRecord.Level, Is.EqualTo(Microsoft.Extensions.Logging.LogLevel.Debug), "Cancellation should be logged as debug");
            Assert.That(result.LogCollector.LatestRecord.Message, Does.Contain("OnError canceled"), "Should log debug when on error canceled");
            Assert.That(result.LogCollector.LatestRecord.Exception, Is.InstanceOf<OperationCanceledException>());
        }
    }

    [Test]
    public async Task Should_not_propagate_header_mutations_from_on_message_to_on_error()
    {
        var originalHeaderKey = "original-header";
        var originalHeaderValue = "original-value";
        var addedHeaderKey = "added-header";

        var message = ServiceBusModelFactory.ServiceBusReceivedMessage(
            messageId: Guid.NewGuid().ToString(),
            properties: new Dictionary<string, object> { { originalHeaderKey, originalHeaderValue } }
        );

        var result = await ProcessMessage(
            message: message,
            onMessage: (msgContext, _) =>
            {
                msgContext.Headers[addedHeaderKey] = "some-value";
                msgContext.Headers[originalHeaderKey] = "some-other-value";
                throw new Exception("force error");
            }
        );

        var headers = result.ErrorContext!.Message.Headers;
        using (Assert.EnterMultipleScope())
        {
            Assert.That(headers.ContainsKey(originalHeaderKey), Is.True, "Original header should still exist in onError");
            Assert.That(headers[originalHeaderKey], Is.EqualTo(originalHeaderValue), "Original header value should be preserved in onError");
            Assert.That(headers.ContainsKey(addedHeaderKey), Is.False, "Added header should NOT be present in onError");
        }
    }

    [Test]
    public async Task Should_dead_letter_if_header_extraction_fails()
    {
        var exception = new Exception("simulated exception");
        var result = await ProcessMessage(headerExtractor: _ => throw exception);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(result.OnMessageWasCalled, Is.False, "OnMessage should not be called if header extraction fails");
            Assert.That(result.OnErrorWasCalled, Is.False, "OnError should not be called if header extraction fails");
            Assert.That(result.MessageActions.WasDeadLettered, Is.True, "Message should be dead lettered");
        }
    }

    [Test]
    public async Task Show_log_and_swallow_exceptions_from_dead_lettering_unless_invocation_is_cancelled()
    {
        var exception = new Exception("dlg failed");
        var messageActions = new TestableMessageActions { DeadLetterMessage = (_, _, _, _, _) => throw exception };
        var result = await ProcessMessage(headerExtractor: _ => throw new Exception("simulated exception"), messageActions: messageActions);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(result.MessageActions.WasDeadLettered, Is.True, "Message should be dead lettered");
            Assert.That(result.LogCollector.LatestRecord.Level, Is.EqualTo(Microsoft.Extensions.Logging.LogLevel.Warning), "Should be logged as warning");
            Assert.That(result.LogCollector.LatestRecord.Exception, Is.SameAs(exception));
        }
    }

    [Test]
    public async Task Show_log_and_swallow_exceptions_from_abandon_unless_invocation_is_cancelled()
    {
        var exception = new Exception("abandon failed");
        var messageActions = new TestableMessageActions { AbandonMessage = (_, _, _) => throw exception };

        var result = await ProcessMessage(
            onMessage: (_, _) => throw new Exception("simulated exception"),
            onError: (_, _) => Task.FromResult(ErrorHandleResult.RetryRequired),
            messageActions: messageActions);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(result.MessageActions.WasAbandoned, Is.True, "Message should be abandoned");
            Assert.That(result.LogCollector.LatestRecord.Level, Is.EqualTo(Microsoft.Extensions.Logging.LogLevel.Warning), "Should be logged as warning");
            Assert.That(result.LogCollector.LatestRecord.Exception, Is.SameAs(exception));
        }
    }

    async Task<ProcessingResult> ProcessMessage(
        ServiceBusReceivedMessage? message = null,
        TestableMessageActions? messageActions = null,
        ICache<string, bool>? completedMessagesCache = null,
        Func<MessageContext, CancellationToken, Task>? onMessage = null,
        Func<ErrorContext, CancellationToken, Task<ErrorHandleResult>>? onError = null,
        Func<ServiceBusReceivedMessage, Dictionary<string, string?>>? headerExtractor = null,
        CancellationToken cancellationToken = default)
    {
        message ??= ServiceBusModelFactory.ServiceBusReceivedMessage();
        onMessage ??= (_, _) => Task.CompletedTask;
        onError ??= (_, _) => Task.FromResult(ErrorHandleResult.RetryRequired);
        messageActions ??= new TestableMessageActions();
        completedMessagesCache ??= new FastConcurrentLru<string, bool>(1_000);


        var fakeLogger = new FakeLogger<PipelineInvokingMessageProcessor>();
        var processor = new PipelineInvokingMessageProcessor(new FakeBaseReceiver(), completedMessagesCache, fakeLogger, headerExtractor);
        MessageContext? capturedMessageContext = null;
        ErrorContext? capturedErrorContext = null;

        await processor.Initialize(PushRuntimeSettings.Default,
            async (msgContext, token) =>
            {
                capturedMessageContext = msgContext;
                await onMessage(msgContext, token);
            },
            async (errorContext, token) =>
            {
                capturedErrorContext = errorContext;
                return await onError(errorContext, token);
            },
            cancellationToken);

        Assert.DoesNotThrowAsync(async () => await processor.Process(message, messageActions, cancellationToken));

        return new ProcessingResult(messageActions, capturedMessageContext, capturedErrorContext, fakeLogger.Collector);
    }

    record ProcessingResult(TestableMessageActions MessageActions, MessageContext? MessageContext, ErrorContext? ErrorContext, FakeLogCollector LogCollector)
    {
        public bool OnMessageWasCalled => MessageContext != null;
        public bool OnErrorWasCalled => ErrorContext != null;
    }

    class TestableMessageActions : ServiceBusMessageActions
    {
        public bool WasCompleted { get; private set; }
        public bool WasAbandoned { get; private set; }
        public bool WasDeadLettered => DeadLetterDetails is not null;
        public DeadLetterCallDetails? DeadLetterDetails { get; private set; }

        public Func<ServiceBusReceivedMessage, CancellationToken, Task>? CompleteMessage { get; set; }
        public Func<ServiceBusReceivedMessage, IDictionary<string, object>?, CancellationToken, Task>? AbandonMessage { get; set; }
        public Func<ServiceBusReceivedMessage, Dictionary<string, object>?, string?, string?, CancellationToken, Task>? DeadLetterMessage { get; set; }

        public override Task CompleteMessageAsync(ServiceBusReceivedMessage message, CancellationToken cancellationToken = new CancellationToken())
        {
            WasCompleted = true;
            return CompleteMessage != null ? CompleteMessage(message, cancellationToken) : Task.CompletedTask;
        }

        public override Task AbandonMessageAsync(ServiceBusReceivedMessage message, IDictionary<string, object>? propertiesToModify = null, CancellationToken cancellationToken = new CancellationToken())
        {
            WasAbandoned = true;
            return AbandonMessage != null ? AbandonMessage(message, propertiesToModify, cancellationToken) : Task.CompletedTask;
        }

        public override Task DeadLetterMessageAsync(ServiceBusReceivedMessage message, Dictionary<string, object>? propertiesToModify = null, string? deadLetterReason = null, string? deadLetterErrorDescription = null, CancellationToken cancellationToken = new CancellationToken())
        {
            DeadLetterDetails = new(deadLetterReason, deadLetterErrorDescription, propertiesToModify);
            return DeadLetterMessage != null ? DeadLetterMessage(message, propertiesToModify, deadLetterReason, deadLetterErrorDescription, cancellationToken) : Task.CompletedTask;
        }

        public record DeadLetterCallDetails(string? DeadLetterReason, string? DeadLetterErrorDescription, Dictionary<string, object>? DeadLetterProperties);
    }

    class FakeBaseReceiver : IMessageReceiver
    {
        public Task Initialize(PushRuntimeSettings limitations, OnMessage onMessage, OnError onError, CancellationToken cancellationToken = new()) => Task.CompletedTask;
        public Task StartReceive(CancellationToken cancellationToken = new()) => throw new NotImplementedException();
        public Task ChangeConcurrency(PushRuntimeSettings limitations, CancellationToken cancellationToken = new()) => throw new NotImplementedException();
        public Task StopReceive(CancellationToken cancellationToken = new()) => throw new NotImplementedException();
        public ISubscriptionManager Subscriptions => null!;
        public string Id => string.Empty;
        public string ReceiveAddress => "TestEndpoint";
    }
}
