namespace NServiceBus.AzureFunctions.Analyzer.Utility;

using System.Reflection;

static class SourceWriterExtensions
{
    extension(SourceWriter writer)
    {
        public SourceWriter PreAmble()
        {
            writer.WriteLine("""
                             // <auto-generated/>
                             
                             #nullable enable annotations
                             #nullable disable warnings
                             
                             // Suppress warnings about [Obsolete] usage in generated code.
                             #pragma warning disable CS0612, CS0618
                             
                             """);
            return writer;
        }

        public SourceWriter WithGeneratedCodeAttribute() => writer.WithGeneratedCodeAttribute(typeof(SourceWriter).Assembly.GetName());

        public SourceWriter WithGeneratedCodeAttribute(AssemblyName assemblyName)
        {
            writer.WriteLine($"""[global::System.CodeDom.Compiler.GeneratedCodeAttribute("{assemblyName.Name}", "{assemblyName.Version!.ToString(3)}")]""");
            return writer;
        }

        public SourceWriter WithOpenNamespace(string? namespaceName)
        {
            if (string.IsNullOrWhiteSpace(namespaceName))
            {
                return writer;
            }

            writer.WriteLine($"namespace {namespaceName}");
            writer.WriteLine("{");
            writer.Indentation++;
            return writer;
        }

        public SourceWriter WithFileScopedNamespace(string? namespaceName)
        {
            if (string.IsNullOrWhiteSpace(namespaceName))
            {
                return writer;
            }

            writer.WriteLine($"namespace {namespaceName};");
            writer.WriteLine();
            return writer;
        }

        public void CloseCurlies()
        {
            while (writer.Indentation > 0)
            {
                writer.Indentation--;
                writer.WriteLine("}");
            }
        }
    }
}
