#nullable enable
namespace NServiceBus.AzureFunctions.Analyzer.Utility;

static class SourceWriterExtensions
{
    extension(SourceWriter writer)
    {
        public SourceWriter PreAmble()
        {
            writer.WriteLine("// <auto-generated/>");
            writer.WriteLine("#nullable enable");
            writer.WriteLine();
            return writer;
        }

        public SourceWriter WithOpenNamespace(string? namespaceName)
        {
            if (string.IsNullOrWhiteSpace(namespaceName))
            {
                return writer;
            }

            writer.WriteLine($"namespace {namespaceName}");
            writer.WriteLine("{");
            writer.Indentation++;
            return writer;
        }

        public void CloseCurlies()
        {
            while (writer.Indentation > 0)
            {
                writer.Indentation--;
                writer.WriteLine("}");
            }
        }
    }
}
