namespace NServiceBus;

using System.ComponentModel;

/// <summary>
/// Identifies source-generated function registration code so that outputs from multiple
/// functions projects can be combined and registered with the Functions runtime.
/// </summary>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
[EditorBrowsable(EditorBrowsableState.Never)]
public sealed class AutoGeneratedFunctionRegistrationsAttribute : Attribute { }
