#nullable enable
namespace NServiceBus.AzureFunctions.Analyzer;

using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

[Generator]
public sealed class FunctionCompositionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var hostProjectInfo = context.AnalyzerConfigOptionsProvider.Select((provider, _) =>
        {
            provider.GlobalOptions.TryGetValue("build_property.OutputType", out var outputType);
            provider.GlobalOptions.TryGetValue("build_property.AzureFunctionsVersion", out var azureFunctionsVersion);
            provider.GlobalOptions.TryGetValue("build_property.RootNamespace", out var rootNamespace);

            var isHost = string.Equals(outputType, "Exe", StringComparison.OrdinalIgnoreCase)
                && !string.IsNullOrEmpty(azureFunctionsVersion);

            return new HostProjectInfo(isHost, rootNamespace);
        });

        var registrationTypesFromReferences = context.CompilationProvider.SelectMany((compilation, ct) =>
        {
            var results = ImmutableArray.CreateBuilder<GeneratedRegistrationClass>();
            foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
            {
                ct.ThrowIfCancellationRequested();
                var className = CompilationAssemblyDetails.FromAssembly(assembly).ToGenerationClassName();
                var fullName = $"NServiceBus.Generated.{className}";
                if (compilation.GetTypeByMetadataName(fullName) is not null)
                {
                    results.Add(new GeneratedRegistrationClass(fullName));
                }
            }
            return results.ToImmutable();
        });

        var collectedRegistrationTypes = registrationTypesFromReferences.Collect();

        var currentAssemblyRegistrationTypeByConvention = context.CompilationProvider
            .Select((compilation, _) => CompilationAssemblyDetails.FromAssembly(compilation.Assembly))
            .Select((assemblyInfo, _) => assemblyInfo.ToGenerationClassName())
            .Select((className, _) => new GeneratedRegistrationClass($"NServiceBus.Generated.{className}"));

        var allData = collectedRegistrationTypes
            .Combine(hostProjectInfo)
            .Combine(currentAssemblyRegistrationTypeByConvention)
            .Select((tuple, _) =>
            {
                var ((regClasses, hostInfo), currentAssemblyClassName) = tuple;

                if (!hostInfo.IsHost)
                {
                    return default;
                }

                var allClasses = regClasses
                    .Concat([currentAssemblyClassName])
                    .Distinct()
                    .ToImmutableArray();

                return new CompositionData(allClasses, hostInfo.RootNamespace);
            });

        context.RegisterSourceOutput(allData, GenerateCompositionCode);
    }

    static void GenerateCompositionCode(SourceProductionContext spc, CompositionData data)
    {
        if (data == default)
        {
            return;
        }

        var regClasses = data.RegistrationClasses;
        var ns = data.RootNamespace;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("public static class NServiceBusFunctionsComposition");
        sb.AppendLine("{");
        sb.AppendLine("    extension(global::Microsoft.Azure.Functions.Worker.Builder.FunctionsApplicationBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        public void AddNServiceBusFunctions()");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(builder);");
        sb.AppendLine("            global::NServiceBus.NServiceBusFunctionsInfrastructure.Initialize(builder);");
        sb.AppendLine();

        foreach (var regClass in regClasses)
        {
            sb.AppendLine($"            foreach (var m in global::{regClass.FullClassName}.GetFunctionManifests())");
            sb.AppendLine($"                global::NServiceBus.FunctionsHostApplicationBuilderExtensions.AddNServiceBusFunction(builder, m);");
        }

        sb.AppendLine();

        foreach (var regClass in regClasses)
        {
            sb.AppendLine($"            foreach (var m in global::{regClass.FullClassName}.GetSendOnlyManifests())");
            sb.AppendLine($"                global::NServiceBus.FunctionsHostApplicationBuilderExtensions.AddSendOnlyNServiceBusEndpoint(builder, m.Name, m.EndpointConfiguration);");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.Append("}");

        spc.AddSource("Composition.g.cs", sb.ToString());
    }

    record struct GeneratedRegistrationClass(string FullClassName);
    record struct HostProjectInfo(bool IsHost, string? RootNamespace);
    record struct CompositionData(
        ImmutableArray<GeneratedRegistrationClass> RegistrationClasses,
        string? RootNamespace);

}