#nullable enable
namespace NServiceBus.AzureFunctions.Analyzer;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

[Generator]
public sealed class FunctionCompositionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var isHostProject = context.AnalyzerConfigOptionsProvider.Select((provider, _) =>
        {
            provider.GlobalOptions.TryGetValue("build_property.OutputType", out var outputType);
            provider.GlobalOptions.TryGetValue("build_property.AzureFunctionsVersion", out var azureFunctionsVersion);

            return string.Equals(outputType, "Exe", System.StringComparison.OrdinalIgnoreCase)
                && !string.IsNullOrEmpty(azureFunctionsVersion);
        });

        var registrationTypesFromCompilation = context.CompilationProvider.SelectMany((compilation, ct) =>
        {
            var attributeType = compilation.GetTypeByMetadataName(MarkerAttributeName);
            if (attributeType is null)
            {
                return ImmutableArray<GeneratedRegistrationClass>.Empty;
            }

            return GetAutoGeneratedRegistrationTypes(compilation.GlobalNamespace, attributeType, ct)
                .ToImmutableArray();
        });

        var collectedRegistrationTypes = registrationTypesFromCompilation.Collect();

        var currentAssemblyRegistrationTypeByConvention = context.CompilationProvider
            .Select((compilation, _) => CompilationAssemblyDetails.FromAssembly(compilation.Assembly))
            .Select((assemblyInfo, _) => assemblyInfo.ToGenerationClassName())
            .Select((className, _) => new GeneratedRegistrationClass($"NServiceBus.Generated.{className}"));

        var allData = collectedRegistrationTypes
            .Combine(isHostProject)
            .Combine(currentAssemblyRegistrationTypeByConvention)
            .Select((tuple, _) =>
            {
                var ((regClasses, isHost), currentAssemblyClassName) = tuple;

                if (!isHost)
                {
                    return default;
                }

                var allClasses = regClasses
                    .Concat([currentAssemblyClassName])
                    .Distinct()
                    .ToImmutableArray();

                return new CompositionData(allClasses, isHost);
            });

        context.RegisterSourceOutput(allData, GenerateCompositionCode);
    }

    static IEnumerable<GeneratedRegistrationClass> GetAutoGeneratedRegistrationTypes(
        INamespaceSymbol ns, INamedTypeSymbol attributeType, CancellationToken cancellationToken)
    {
        foreach (var type in ns.GetTypeMembers())
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (type.GetAttributes().Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attributeType)))
            {
                yield return new GeneratedRegistrationClass(type.ToDisplayString());
            }
        }

        foreach (var childNamespace in ns.GetNamespaceMembers())
        {
            foreach (var reg in GetAutoGeneratedRegistrationTypes(childNamespace, attributeType, cancellationToken))
            {
                yield return reg;
            }
        }
    }

    static void GenerateCompositionCode(SourceProductionContext spc, CompositionData data)
    {
        if (data == default)
        {
            return;
        }

        var regClasses = data.RegistrationClasses;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace NServiceBus");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public static class NServiceBusFunctionsComposition");
        sb.AppendLine("    {");
        sb.AppendLine("        public static void AddNServiceBusFunctions(");
        sb.AppendLine("            this global::Microsoft.Azure.Functions.Worker.Builder.FunctionsApplicationBuilder builder)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(builder);");
        sb.AppendLine("            global::NServiceBus.NServiceBusFunctionsInfrastructure.Initialize(builder);");
        sb.AppendLine();

        foreach (var regClass in regClasses)
        {
            sb.AppendLine($"            foreach (var m in global::{regClass.FullClassName}.GetFunctionManifests())");
            sb.AppendLine($"                global::NServiceBus.FunctionsHostApplicationBuilderExtensions.AddNServiceBusFunction(builder, m);");
        }

        sb.AppendLine();

        foreach (var regClass in regClasses)
        {
            sb.AppendLine($"            foreach (var m in global::{regClass.FullClassName}.GetSendOnlyManifests())");
            sb.AppendLine($"                global::NServiceBus.FunctionsHostApplicationBuilderExtensions.AddSendOnlyNServiceBusEndpoint(builder, m.Name, m.EndpointConfiguration);");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.Append("}");

        spc.AddSource("Composition.g.cs", sb.ToString());
    }

    record struct GeneratedRegistrationClass(string FullClassName);
    record struct CompositionData(
        ImmutableArray<GeneratedRegistrationClass> RegistrationClasses,
        bool IsHostProject);

    const string MarkerAttributeName = "NServiceBus.AutoGeneratedFunctionRegistrationsAttribute";
}