#nullable enable
namespace NServiceBus.AzureFunctions.Analyzer;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;

[Generator]
public sealed class FunctionCompositionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var methodsToIntercept = context.SyntaxProvider
            .CreateSyntaxProvider(SyntaxLooksLikeAddNServiceBusFunctions, TransformToInterceptor)
            .Where(candidate => candidate is not null);

        var registrationTypesFromCompilation = context.CompilationProvider.SelectMany((compilation, ct) =>
        {
            var attributeType = compilation.GetTypeByMetadataName(MarkerAttributeName);
            if (attributeType is null)
            {
                return ImmutableArray<GeneratedRegistrationClass>.Empty;
            }

            return GetAutoGeneratedRegistrationTypes(compilation.GlobalNamespace, attributeType, ct)
                .ToImmutableArray();
        });

        var collectedRegistrationTypes = registrationTypesFromCompilation.Collect();
        var collectedInterceptorLocations = methodsToIntercept.Collect();

        var currentAssemblyRegistrationTypeByConvention = context.CompilationProvider
            .Select((compilation, _) => CompilationAssemblyDetails.FromAssembly(compilation.Assembly))
            .Select((assemblyInfo, _) => assemblyInfo.ToGenerationClassName())
            .Select((className, _) => new GeneratedRegistrationClass($"NServiceBus.Generated.{className}"));

        var allDataForInterceptor = collectedRegistrationTypes
            .Combine(collectedInterceptorLocations)
            .Combine(currentAssemblyRegistrationTypeByConvention)
            .Select((tuple, _) =>
            {
                var ((regClasses, interceptorLocations), currentAssemblyClassName) = tuple;

                if (!interceptorLocations.Any())
                {
                    return default;
                }

                var allClasses = regClasses
                    .Concat([currentAssemblyClassName])
                    .Distinct()
                    .ToImmutableArray();

                return new InterceptorData(allClasses, interceptorLocations);
            });

        context.RegisterSourceOutput(allDataForInterceptor, GenerateInterceptorCode);
    }

    static bool SyntaxLooksLikeAddNServiceBusFunctions(SyntaxNode node, CancellationToken cancellationToken) =>
        node is InvocationExpressionSyntax { Expression: MemberAccessExpressionSyntax { Name.Identifier.ValueText: MethodName } };

    static InterceptDetails? TransformToInterceptor(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        if (context.Node is not InvocationExpressionSyntax { Expression: MemberAccessExpressionSyntax } invocation)
        {
            return null;
        }

        if (context.SemanticModel.GetOperation(invocation, cancellationToken) is not IInvocationOperation operation)
        {
            return null;
        }

        if (operation.TargetMethod is not
            {
                Name: MethodName,
                ContainingType:
                {
                    Name: ExtensionClassName,
                    ContainingNamespace: { Name: "NServiceBus", ContainingNamespace.IsGlobalNamespace: true }
                }
            })
        {
            return null;
        }

        if (context.SemanticModel.GetInterceptableLocation(invocation, cancellationToken) is not { } location)
        {
            return null;
        }

        return new InterceptDetails(location);
    }

    static IEnumerable<GeneratedRegistrationClass> GetAutoGeneratedRegistrationTypes(
        INamespaceSymbol ns, INamedTypeSymbol attributeType, CancellationToken cancellationToken)
    {
        foreach (var type in ns.GetTypeMembers())
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (type.GetAttributes().Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attributeType)))
            {
                yield return new GeneratedRegistrationClass(type.ToDisplayString());
            }
        }

        foreach (var childNamespace in ns.GetNamespaceMembers())
        {
            foreach (var reg in GetAutoGeneratedRegistrationTypes(childNamespace, attributeType, cancellationToken))
            {
                yield return reg;
            }
        }
    }

    static void GenerateInterceptorCode(SourceProductionContext spc, InterceptorData data)
    {
        if (data == default)
        {
            return;
        }

        var (regClasses, interceptLocations) = data;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Diagnostics.Conditional(\"DEBUG\")]");
        sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    sealed file class InterceptsLocationAttribute : global::System.Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public InterceptsLocationAttribute(int version, string data)");
        sb.AppendLine("        {");
        sb.AppendLine("            _ = version;");
        sb.AppendLine("            _ = data;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("namespace NServiceBus");
        sb.AppendLine("{");
        sb.AppendLine("    static file class NServiceBusFunctionsInterceptors");
        sb.AppendLine("    {");

        foreach (var location in interceptLocations)
        {
            if (location is not null)
            {
                sb.AppendLine($"        [global::System.Runtime.CompilerServices.InterceptsLocation({location.Value.Location.Version}, \"{location.Value.Location.Data}\")] // {location.Value.Location.GetDisplayLocation()}");
            }
        }

        sb.AppendLine("        public static void AddNServiceBusFunctions(");
        sb.AppendLine("            this global::Microsoft.Azure.Functions.Worker.Builder.FunctionsApplicationBuilder builder)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(builder);");
        sb.AppendLine("            global::NServiceBus.NServiceBusFunctionsInfrastructure.Initialize(builder);");
        sb.AppendLine();

        foreach (var regClass in regClasses)
        {
            sb.AppendLine($"            foreach (var m in global::{regClass.FullClassName}.GetFunctionManifests())");
            sb.AppendLine($"                global::NServiceBus.FunctionsHostApplicationBuilderExtensions.AddNServiceBusFunction(builder, m);");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("Interception.g.cs", sb.ToString());
    }

    record struct GeneratedRegistrationClass(string FullClassName);
    record struct InterceptDetails(InterceptableLocation Location);
    record struct InterceptorData(
        ImmutableArray<GeneratedRegistrationClass> RegistrationClasses,
        ImmutableArray<InterceptDetails?> Locations);

    const string MarkerAttributeName = "NServiceBus.AutoGeneratedFunctionRegistrationsAttribute";
    const string ExtensionClassName = "NServiceBusFunctionsSourceGenExtensions";
    const string MethodName = "AddNServiceBusFunctions";
}