namespace NServiceBus.AzureFunctions.Analyzer;

using System;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Utility;

public sealed partial class FunctionEndpointGenerator
{
    static class Emitter
    {
        public static void Emit(SourceProductionContext spc, ImmutableArray<FunctionSpec> functions, string assemblyClassName)
        {
            if (functions.Length <= 0)
            {
                return;
            }

            EmitMethodBodies(spc, functions);
            EmitRegistration(spc, functions, assemblyClassName);
        }

        static void EmitMethodBodies(SourceProductionContext spc, ImmutableArray<FunctionSpec> functions)
        {
            var writer = new SourceWriter();
            writer.PreAmble();
            writer.WriteLine("using Microsoft.Extensions.DependencyInjection;");

            var groups = functions
                .GroupBy(f => (f.ContainingNamespace, f.ContainingClassName))
                .OrderBy(g => g.Key.ContainingNamespace, StringComparer.Ordinal)
                .ThenBy(g => g.Key.ContainingClassName, StringComparer.Ordinal);

            foreach (var group in groups)
            {
                writer.WriteLine();
                var namespaceOpened = !string.IsNullOrWhiteSpace(group.Key.ContainingNamespace);
                writer.WithOpenNamespace(group.Key.ContainingNamespace);
                writer.WriteLine($"public partial class {group.Key.ContainingClassName}");
                writer.WriteLine("{");
                writer.Indentation++;

                bool first = true;
                foreach (var func in group.OrderBy(f => f.MethodName, StringComparer.Ordinal))
                {
                    if (!first)
                    {
                        writer.WriteLine();
                    }

                    first = false;

                    writer.WithGeneratedCodeAttribute();
                    writer.WriteLine($"{func.Accessibility} partial {func.ReturnType} {func.MethodName}(");
                    writer.WriteLine($"    {func.ParameterList})");
                    writer.WriteLine("{");
                    writer.Indentation++;
                    writer.WriteLine($"var processor = {func.FunctionContextParamName}.InstanceServices");
                    writer.WriteLine($"    .GetRequiredKeyedService<{func.ProcessorTypeFullyQualified}>(\"{func.FunctionName}\");");
                    writer.WriteLine($"return {func.ProcessCallExpression};");
                    writer.Indentation--;
                    writer.WriteLine("}");
                }

                writer.Indentation--;
                writer.WriteLine("}");
                if (namespaceOpened)
                {
                    writer.Indentation--;
                    writer.WriteLine("}");
                }
            }

            spc.AddSource("FunctionMethodBodies.g.cs", writer.ToSourceText());
        }

        static void EmitRegistration(SourceProductionContext spc, ImmutableArray<FunctionSpec> functions, string assemblyClassName)
        {
            var writer = new SourceWriter();
            writer.PreAmble();
            writer.WithFileScopedNamespace("NServiceBus.Generated");
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// Registrations for NServiceBus functions in this assembly.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
            writer.WriteLine("[global::NServiceBus.AutoGeneratedFunctionRegistrationsAttribute]");
            writer.WithGeneratedCodeAttribute();
            writer.WriteLine($"public static class {assemblyClassName}");
            writer.WriteLine("{");
            writer.Indentation++;
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// Gets function manifests for NServiceBus functions in this assembly.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("public static global::System.Collections.Generic.IEnumerable<global::NServiceBus.FunctionManifest>");
            writer.WriteLine("    GetFunctionManifests()");
            writer.WriteLine("{");
            writer.Indentation++;

            foreach (var func in functions.OrderBy(f => f.FunctionName, StringComparer.Ordinal))
            {
                writer.WriteLine("yield return new global::NServiceBus.FunctionManifest(");
                writer.WriteLine($"    \"{func.FunctionName}\", \"{func.AddressName}\", \"{func.ConnectionSettingName}\",");
                writer.WriteLine($"    {GenerateConfigureMethodCall(func.ConfigureMethod)},");
                writer.WriteLine($"    {func.RegistrationMethodFullyQualified});");
            }

            writer.WriteLine("yield break;");
            writer.CloseCurlies();

            spc.AddSource("FunctionRegistration.g.cs", writer.ToSourceText());
        }

        static string GenerateConfigureMethodCall(ConfigureMethodSpec configureMethod)
        {
            var argumentList = string.Join(", ", configureMethod.ParameterTypeNames);
            return $"(endpointconfiguration, iservicecollection, iconfiguration, ihostenvironment) => {configureMethod.ContainingTypeFullyQualified}.{configureMethod.MethodName}({argumentList})";
        }
    }
}
