namespace NServiceBus.AzureFunctions.Analyzer;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using NServiceBus.AzureFunctions.Analyzer.Utility;

public sealed partial class FunctionEndpointGenerator
{
    static class Emitter
    {
        static readonly Dictionary<string, DiagnosticDescriptor> Descriptors = new()
        {
            [DiagnosticIds.ClassMustBePartial] = DiagnosticIds.ClassMustBePartialDescriptor,
            [DiagnosticIds.ShouldNotImplementIHandleMessages] = DiagnosticIds.ShouldNotImplementIHandleMessagesDescriptor,
            [DiagnosticIds.MethodMustBePartial] = DiagnosticIds.MethodMustBePartialDescriptor,
            [DiagnosticIds.MultipleConfigureMethods] = DiagnosticIds.MultipleConfigureMethodsDescriptor,
        };

        public static void ReportDiagnostic(SourceProductionContext spc, DiagnosticSpec spec)
        {
            if (!Descriptors.TryGetValue(spec.DescriptorId, out var descriptor))
            {
                return;
            }

            var location = string.IsNullOrEmpty(spec.FilePath)
                ? Location.None
                : Location.Create(spec.FilePath, spec.Span, spec.LineSpan);

            var args = new object[spec.Arguments.Count];
            for (int i = 0; i < spec.Arguments.Count; i++)
            {
                args[i] = spec.Arguments[i];
            }

            spc.ReportDiagnostic(Diagnostic.Create(descriptor, location, args));
        }

        public static void Emit(SourceProductionContext spc, ImmutableArray<FunctionSpec> functions, string assemblyClassName)
        {
            if (functions.Length > 0)
            {
                EmitMethodBodies(spc, functions);
            }

            EmitRegistration(spc, functions, assemblyClassName);
        }

        static void EmitMethodBodies(SourceProductionContext spc, ImmutableArray<FunctionSpec> functions)
        {
            var writer = new SourceWriter();
            writer.WriteLine("// <auto-generated/>");
            writer.WriteLine("using Microsoft.Extensions.DependencyInjection;");

            var groups = functions
                .GroupBy(f => (f.ContainingNamespace, f.ContainingClassName))
                .OrderBy(g => g.Key.ContainingNamespace, StringComparer.Ordinal)
                .ThenBy(g => g.Key.ContainingClassName, StringComparer.Ordinal);

            foreach (var group in groups)
            {
                writer.WriteLine();
                writer.WriteLine($"namespace {group.Key.ContainingNamespace}");
                writer.WriteLine("{");
                writer.Indentation++;
                writer.WriteLine($"public partial class {group.Key.ContainingClassName}");
                writer.WriteLine("{");
                writer.Indentation++;

                bool first = true;
                foreach (var func in group.OrderBy(f => f.MethodName, StringComparer.Ordinal))
                {
                    if (!first)
                    {
                        writer.WriteLine();
                    }

                    first = false;

                    writer.WriteLine($"{func.Accessibility} partial {func.ReturnType} {func.MethodName}(");
                    writer.WriteLine($"    {func.ParameterList})");
                    writer.WriteLine("{");
                    writer.Indentation++;
                    writer.WriteLine($"var processor = {func.FunctionContextParamName}.InstanceServices");
                    writer.WriteLine($"    .GetKeyedService<global::NServiceBus.AzureFunctions.AzureServiceBus.MessageProcessor>(\"{func.FunctionName}\");");
                    writer.WriteLine("if (processor is null)");
                    writer.WriteLine("{");
                    writer.Indentation++;
                    writer.WriteLine($"throw new global::System.InvalidOperationException(\"{func.FunctionName} has not been registered.\");");
                    writer.Indentation--;
                    writer.WriteLine("}");
                    writer.WriteLine($"return processor.Process({func.MessageParamName}, {func.FunctionContextParamName}, {func.CancellationTokenParamName});");
                    writer.Indentation--;
                    writer.WriteLine("}");
                }

                writer.Indentation--;
                writer.WriteLine("}");
                writer.Indentation--;
                writer.WriteLine("}");
            }

            spc.AddSource("FunctionMethodBodies.g.cs", writer.ToSourceText());
        }

        static void EmitRegistration(SourceProductionContext spc, ImmutableArray<FunctionSpec> functions, string assemblyClassName)
        {
            var writer = new SourceWriter();
            writer.WriteLine("// <auto-generated/>");
            writer.WriteLine("namespace NServiceBus.Generated");
            writer.WriteLine("{");
            writer.Indentation++;
            writer.WriteLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
            writer.WriteLine("[global::NServiceBus.AutoGeneratedFunctionRegistrationsAttribute]");
            writer.WriteLine($"public static class {assemblyClassName}");
            writer.WriteLine("{");
            writer.Indentation++;
            writer.WriteLine("public static global::System.Collections.Generic.IEnumerable<global::NServiceBus.FunctionManifest>");
            writer.WriteLine("    GetFunctionManifests()");
            writer.WriteLine("{");
            writer.Indentation++;

            foreach (var func in functions.OrderBy(f => f.FunctionName, StringComparer.Ordinal))
            {
                writer.WriteLine("yield return new global::NServiceBus.FunctionManifest(");
                writer.WriteLine($"    \"{func.FunctionName}\", \"{func.QueueName}\", \"{func.ConnectionName}\",");
                writer.WriteLine($"    {GenerateConfigureMethodCall(func.ConfigureMethod)});");
            }

            writer.WriteLine("yield break;");
            writer.CloseCurlies();

            spc.AddSource("FunctionRegistration.g.cs", writer.ToSourceText());
        }

        static string GenerateConfigureMethodCall(ConfigureMethodSpec configureMethod)
        {
            var argumentList = string.Join(", ", configureMethod.ParameterTypeNames);
            return $"(endpointconfiguration, iconfiguration, ihostenvironment) => {configureMethod.ContainingTypeFullyQualified}.{configureMethod.MethodName}({argumentList})";
        }
    }
}