#nullable enable
namespace NServiceBus.AzureFunctions.Analyzer;

using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class MissingCompositionCallAnalyzer : DiagnosticAnalyzer
{
    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => [DiagnosticIds.MissingAddNServiceBusFunctionsCallDescriptor];

    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();
        context.RegisterCompilationStartAction(OnCompilationStart);
    }

    static void OnCompilationStart(CompilationStartAnalysisContext context)
    {
        var globalOptions = context.Options.AnalyzerConfigOptionsProvider.GlobalOptions;
        globalOptions.TryGetValue("build_property.OutputType", out var outputType);
        globalOptions.TryGetValue("build_property.AzureFunctionsVersion", out var azureFunctionsVersion);
        globalOptions.TryGetValue("build_property.RootNamespace", out var rootNamespace);

        var isExeOutput = string.Equals(outputType, "Exe", StringComparison.OrdinalIgnoreCase)
            || context.Compilation.Options.OutputKind is OutputKind.ConsoleApplication or OutputKind.WindowsApplication;
        var isAzureFunctionsProject = !string.IsNullOrEmpty(azureFunctionsVersion)
            || context.Compilation.GetTypeByMetadataName("Microsoft.Azure.Functions.Worker.FunctionAttribute") is not null;

        if (!isExeOutput || !isAzureFunctionsProject)
        {
            return;
        }

        if (!HasAutoGeneratedRegistrationTypes(context.Compilation, context.CancellationToken))
        {
            return;
        }

        var expectedCompositionNamespace = string.IsNullOrWhiteSpace(rootNamespace)
            ? InferCompositionNamespace(context.Compilation, context.CancellationToken)
            : rootNamespace;

        var callFound = 0;

        context.RegisterSyntaxNodeAction(nodeContext =>
        {
            if (Volatile.Read(ref callFound) != 0)
            {
                return;
            }

            if (nodeContext.Node is InvocationExpressionSyntax
                {
                    Expression: MemberAccessExpressionSyntax
                    {
                        Name.Identifier.ValueText: MethodName
                    }
                } invocation
                && nodeContext.SemanticModel.GetSymbolInfo(invocation, nodeContext.CancellationToken).Symbol is IMethodSymbol method
                && HasContainingType(method, CompositionClassName, expectedCompositionNamespace))
            {
                Interlocked.Exchange(ref callFound, 1);
            }
        }, SyntaxKind.InvocationExpression);

        context.RegisterCompilationEndAction(endContext =>
        {
            if (Volatile.Read(ref callFound) == 0)
            {
                var location = endContext.Compilation.SyntaxTrees
                    .Select(tree => tree.GetRoot(endContext.CancellationToken).GetFirstToken())
                    .Where(static token => token != default)
                    .Select(static token => token.GetLocation())
                    .FirstOrDefault() ?? Location.None;

                endContext.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticIds.MissingAddNServiceBusFunctionsCallDescriptor,
                    location));
            }
        });
    }

    static bool HasAutoGeneratedRegistrationTypes(Compilation compilation, CancellationToken cancellationToken)
    {
        var currentClassName = CompilationAssemblyDetails.FromAssembly(compilation.Assembly).ToGenerationClassName();
        if (compilation.GetTypeByMetadataName($"NServiceBus.Generated.{currentClassName}") is not null)
        {
            return true;
        }

        foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var className = CompilationAssemblyDetails.FromAssembly(assembly).ToGenerationClassName();
            if (compilation.GetTypeByMetadataName($"NServiceBus.Generated.{className}") is not null)
            {
                return true;
            }
        }

        return false;
    }

    static string? InferCompositionNamespace(Compilation compilation, CancellationToken cancellationToken)
    {
        foreach (var syntaxTree in compilation.SyntaxTrees)
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (!syntaxTree.FilePath.Replace('\\', '/').EndsWith("FunctionCompositionGenerator/Composition.cs", StringComparison.Ordinal))
            {
                continue;
            }

            var root = syntaxTree.GetRoot(cancellationToken);
            var classDeclaration = root.DescendantNodes()
                .OfType<ClassDeclarationSyntax>()
                .FirstOrDefault(static declaration => declaration.Identifier.ValueText == CompositionClassName);

            if (classDeclaration is null)
            {
                continue;
            }

            var namespaceParts = classDeclaration.Ancestors()
                .OfType<BaseNamespaceDeclarationSyntax>()
                .Select(static declaration => declaration.Name.ToString())
                .Reverse()
                .ToArray();

            return namespaceParts.Length == 0
                ? null
                : string.Join(".", namespaceParts);
        }

        return null;
    }

    static bool HasContainingType(IMethodSymbol method, string typeName, string? rootNamespace)
    {
        // C# 14 extension members nest inside a synthetic extension block type,
        // so ContainingType is the extension block, not the enclosing static class.
        // Walk up the ContainingType chain to find the class.
        var type = method.ContainingType;
        while (type is not null)
        {
            if (type.Name == typeName)
            {
                if (string.IsNullOrWhiteSpace(rootNamespace))
                {
                    return true;
                }

                return string.Equals(type.ContainingNamespace.ToDisplayString(), rootNamespace, StringComparison.Ordinal);
            }
            type = type.ContainingType;
        }
        return false;
    }

    const string MethodName = "AddNServiceBusFunctions";
    const string CompositionClassName = "NServiceBusFunctionsComposition";
}