#nullable enable
namespace NServiceBus.AzureFunctions.Analyzer;

using System.Collections.Immutable;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class MissingCompositionCallAnalyzer : DiagnosticAnalyzer
{
    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics =>
        ImmutableArray.Create(DiagnosticIds.MissingAddNServiceBusFunctionsCallDescriptor);

    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();
        context.RegisterCompilationStartAction(OnCompilationStart);
    }

    static void OnCompilationStart(CompilationStartAnalysisContext context)
    {
        var globalOptions = context.Options.AnalyzerConfigOptionsProvider.GlobalOptions;
        globalOptions.TryGetValue("build_property.OutputType", out var outputType);
        globalOptions.TryGetValue("build_property.AzureFunctionsVersion", out var azureFunctionsVersion);

        if (!string.Equals(outputType, "Exe", StringComparison.OrdinalIgnoreCase)
            || string.IsNullOrEmpty(azureFunctionsVersion))
        {
            return;
        }

        if (!HasAutoGeneratedRegistrationTypes(context.Compilation, context.CancellationToken))
        {
            return;
        }

        var callFound = 0;

        context.RegisterSyntaxNodeAction(nodeContext =>
        {
            if (Volatile.Read(ref callFound) != 0)
            {
                return;
            }

            if (nodeContext.Node is InvocationExpressionSyntax
                {
                    Expression: MemberAccessExpressionSyntax
                    {
                        Name.Identifier.ValueText: MethodName
                    }
                } invocation
                && nodeContext.SemanticModel.GetSymbolInfo(invocation, nodeContext.CancellationToken).Symbol is IMethodSymbol method
                && HasContainingType(method, CompositionClassName))
            {
                Interlocked.Exchange(ref callFound, 1);
            }
        }, SyntaxKind.InvocationExpression);

        context.RegisterCompilationEndAction(endContext =>
        {
            if (Volatile.Read(ref callFound) == 0)
            {
                endContext.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticIds.MissingAddNServiceBusFunctionsCallDescriptor,
                    Location.None));
            }
        });
    }

    static bool HasAutoGeneratedRegistrationTypes(Compilation compilation, CancellationToken cancellationToken)
    {
        var currentClassName = CompilationAssemblyDetails.FromAssembly(compilation.Assembly).ToGenerationClassName();
        if (compilation.GetTypeByMetadataName($"NServiceBus.Generated.{currentClassName}") is not null)
        {
            return true;
        }

        foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var className = CompilationAssemblyDetails.FromAssembly(assembly).ToGenerationClassName();
            if (compilation.GetTypeByMetadataName($"NServiceBus.Generated.{className}") is not null)
            {
                return true;
            }
        }

        return false;
    }

    static bool HasContainingType(IMethodSymbol method, string typeName)
    {
        // C# 14 extension members nest inside a synthetic extension block type,
        // so ContainingType is the extension block, not the enclosing static class.
        // Walk up the ContainingType chain to find the class.
        var type = method.ContainingType;
        while (type is not null)
        {
            if (type.Name == typeName)
            {
                return true;
            }
            type = type.ContainingType;
        }
        return false;
    }

    const string MethodName = "AddNServiceBusFunctions";
    const string CompositionClassName = "NServiceBusFunctionsComposition";
}