#nullable enable
namespace NServiceBus.AzureFunctions.Analyzer;

using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class MissingCompositionCallAnalyzer : DiagnosticAnalyzer
{
    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics =>
        ImmutableArray.Create(DiagnosticIds.MissingAddNServiceBusFunctionsCallDescriptor);

    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();
        context.RegisterCompilationStartAction(OnCompilationStart);
    }

    static void OnCompilationStart(CompilationStartAnalysisContext context)
    {
        var globalOptions = context.Options.AnalyzerConfigOptionsProvider.GlobalOptions;
        globalOptions.TryGetValue("build_property.OutputType", out var outputType);
        globalOptions.TryGetValue("build_property.AzureFunctionsVersion", out var azureFunctionsVersion);

        if (!string.Equals(outputType, "Exe", System.StringComparison.OrdinalIgnoreCase)
            || string.IsNullOrEmpty(azureFunctionsVersion))
        {
            return;
        }

        var markerAttribute = context.Compilation.GetTypeByMetadataName(MarkerAttributeName);
        if (markerAttribute is null)
        {
            return;
        }

        if (!HasAutoGeneratedRegistrationTypes(context.Compilation.GlobalNamespace, markerAttribute, context.CancellationToken))
        {
            return;
        }

        var callFound = 0;

        context.RegisterSyntaxNodeAction(nodeContext =>
        {
            if (Volatile.Read(ref callFound) != 0)
            {
                return;
            }

            if (nodeContext.Node is InvocationExpressionSyntax
                {
                    Expression: MemberAccessExpressionSyntax
                    {
                        Name.Identifier.ValueText: MethodName
                    }
                })
            {
                Interlocked.Exchange(ref callFound, 1);
            }
        }, SyntaxKind.InvocationExpression);

        context.RegisterCompilationEndAction(endContext =>
        {
            if (Volatile.Read(ref callFound) == 0)
            {
                endContext.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticIds.MissingAddNServiceBusFunctionsCallDescriptor,
                    Location.None));
            }
        });
    }

    static bool HasAutoGeneratedRegistrationTypes(
        INamespaceSymbol ns, INamedTypeSymbol attributeType, CancellationToken cancellationToken)
    {
        foreach (var type in ns.GetTypeMembers())
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (type.GetAttributes().Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attributeType)))
            {
                return true;
            }
        }

        foreach (var childNamespace in ns.GetNamespaceMembers())
        {
            if (HasAutoGeneratedRegistrationTypes(childNamespace, attributeType, cancellationToken))
            {
                return true;
            }
        }

        return false;
    }

    const string MarkerAttributeName = "NServiceBus.AutoGeneratedFunctionRegistrationsAttribute";
    const string MethodName = "AddNServiceBusFunctions";
}