namespace NServiceBus.AzureFunctions.Analyzer;

using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Utility;

public sealed partial class SendOnlyEndpointGenerator
{
    static class Emitter
    {
        public static void Emit(SourceProductionContext spc, ImmutableArray<SendOnlyEndpointSpec> sendOnlyEndpoints, string assemblyClassName)
        {
            if (sendOnlyEndpoints.Length <= 0)
            {
                return;
            }

            var writer = new SourceWriter();
            writer.PreAmble();
            writer.WithFileScopedNamespace("NServiceBus.Generated");
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// Registrations for NServiceBus send-only endpoints in this assembly.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
            writer.WriteLine("[global::NServiceBus.AutoGeneratedFunctionRegistrationsAttribute]");
            writer.WithGeneratedCodeAttribute();
            writer.WriteLine($"public static class {assemblyClassName}");
            writer.WriteLine("{");
            writer.Indentation++;
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// Gets function manifests for NServiceBus functions in this assembly.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("public static global::System.Collections.Generic.IEnumerable<global::NServiceBus.FunctionManifest>");
            writer.WriteLine("    GetFunctionManifests()");
            writer.WriteLine("{");
            writer.Indentation++;
            writer.WriteLine("yield break;");
            writer.Indentation--;
            writer.WriteLine("}");
            writer.WriteLine();
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// Gets send-only endpoint manifests for NServiceBus endpoints in this assembly.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("public static global::System.Collections.Generic.IEnumerable<global::NServiceBus.SendOnlyEndpointManifest>");
            writer.WriteLine("    GetSendOnlyEndpointManifests()");
            writer.WriteLine("{");
            writer.Indentation++;

            foreach (var endpoint in sendOnlyEndpoints.OrderBy(f => f.EndpointName, StringComparer.Ordinal))
            {
                writer.WriteLine("yield return new global::NServiceBus.SendOnlyEndpointManifest(");
                writer.WriteLine($"    \"{endpoint.EndpointName}\",");
                writer.WriteLine($"    {GenerateConfigureMethodCall(endpoint.ConfigureMethod)},");
                writer.WriteLine($"    {endpoint.RegistrationMethodFullyQualified});");
            }

            writer.WriteLine("yield break;");
            writer.Indentation--;
            writer.WriteLine("}");
            writer.Indentation--;
            writer.WriteLine("}");

            spc.AddSource("SendOnlyEndpointRegistration.g.cs", writer.ToSourceText());
        }

        static string GenerateConfigureMethodCall(ConfigureMethodSpec configureMethod)
        {
            var argumentList = string.Join(", ", configureMethod.ParameterTypeNames);
            return $"(endpointconfiguration, iservicecollection, iconfiguration, ihostenvironment) => {configureMethod.ContainingTypeFullyQualified}.{configureMethod.MethodName}({argumentList})";
        }
    }
}