namespace NServiceBus;

using System.ComponentModel;

[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
[EditorBrowsable(EditorBrowsableState.Never)]
public sealed class AutoGeneratedFunctionRegistrationsAttribute : Attribute { }